con_pro:con_pro.cpp
	g++ $^ -o $@ -lpthread
pro_con:pro_con.cpp
	g++ $^ -o $@ -lpthread
cond:cond.c
	gcc $^ -o $@ -lpthread #-pthread
mutex:mutex.c
	gcc $^ -o $@ -lpthread #-pthread
create:create.c
	gcc $^ -o $@ -lpthread #-pthread
